######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 28 13:51:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

INCLUDEPATH += . ../../../src ../../../src/qt4 ../../../src/include
LIBS += -L../../../lib/ -lqttracker

# Input
SOURCES += main.cpp
