######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 23 13:44:55 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

INCLUDEPATH += . ../../../src ../../../src/qt4 ../../../src/include
LIBS += -L../../../lib/ -lqttracker

# Input
HEADERS += model.hh
SOURCES += main.cpp
