######################################################################
# Automatically generated by qmake (2.01a) Fri May 22 18:17:11 2009
######################################################################
CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .

INCLUDEPATH += . ../../../src ../../../src/qt4 ../../../src/include
LIBS += -L../../../lib/ -lqttracker

# Input
SOURCES += nmm.cpp
