# #####################################################################
# Automatically generated by qmake (2.01a) Tue Jul 14 13:38:03 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .

INCLUDEPATH += . ../../../src ../../../src/qt4 ../../../src/include
LIBS += -L../../../lib/ -lqttracker


# Input
SOURCES += main.cpp \
    bookmarkeditor.cpp
FORMS += bookmarkeditor.ui
HEADERS += bookmarkeditor.h \
    bookmarkeditor.h
