/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TrackerNodesProxy -p tracker_resources -i dbus_types.h tracker-resources.xml org.freedesktop.Tracker1.Resources
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "tracker_resources.h"

/*
 * Implementation of interface class TrackerNodesProxy
 */

TrackerNodesProxy::TrackerNodesProxy
		( const QString &service, const QString &path, const QDBusConnection &connection
		, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
	, service_(service), path_(path), connection_(connection)
{
}

TrackerNodesProxy::~TrackerNodesProxy()
{
	QDBusConnection::disconnectFromBus(connection_.name());
}

